### ISSUE TITLE
JavaScript Error with the GUI version likely due to OS language

### ISSUE THREAD

**Issue by roc-italy** [henrikstengaard/hst-imager#1]
Hello Henrik,

First of all, thank you so much for this great utility. I have been using the console version, which works just fine in creating PFS3 images while formatting them. To the best of my knowledge, it is the only utility capable to do so and my powershell scripts has been updated accordingly.

I believe there is a little glitch  in the GUI portable (and zipped) versions. On my Windows 10 22H2 x64, the portable version returns a Javascript exeption "uncaught exception: ENOENT..". 

I guess the issue is that the error says that it expects "C:\Users\roc\AppData...." but I realised my OS in in Italian with something like "C:\Utenti\roc\AppData". I tried all the three portable versions and launched them either elevated or with standard user.

![image](https://user-images.githubusercontent.com/40177821/204628456-9bd43070-eff4-49d9-b530-07630cb935c9.png)

Would it be possible to invoke something like %userprofile% which maps directly regardless of the language or to use the portable folder where it actually runs?

Regardless, If you would be open to some additional little features to Hst-imager, I could suggest a few more in case some of them would be feasible and felt useful for all.

Again. Small glitch, gret util ;-) Tak.

**Comment by henrikstengaard** [comment]
This error comes from Electron framework used and I will look into the issue for a possible fix.

For features/suggestions, please create a new issues for each feature/suggestion.

**Comment by henrikstengaard** [comment]
The Javascript spawn error on startup of gui version has been fixed with latest prerelease of Hst Imager v0.9.250 at https://github.com/henrikstengaard/hst-imager/releases.

Note that the gui version currently lacks a lot of features compared to console version mostly those covering partitioning and formatting.
