### ISSUE TITLE
hst-imager_v1.2.390 GUI window actions and "whitelisting on Windows"

### ISSUE THREAD

**Issue by ManuelAndre123** [henrikstengaard/hst-imager#17]
Minimize, Maximize and close buttons (top right in the Windows GUI version) do not work.

Left hand side "old"  controls, Move, Change Format, Minimize/Maximize and Close work.

Also the HST-program folder has to be whitelisted with "DefenderUI" or Windows Security.
Else you will receive an error and the program will not start.

**Comment by mja65** [comment]
I checked the Mac version and the buttons also do not work there so that part of the issue is not Windows specific it seems
