### ISSUE TITLE
 HST Imager GUI version on Mac will not proceed past Terms and Conditions

### ISSUE THREAD

**Issue by mja65** [henrikstengaard/hst-imager#18]
Running the Mac version (on Sonoma) for the latest release will not allow me to proceed past the Ts and Cs. I get to the screen asking me to agree or disagree but I cannot click on Agree to continue. 

The button presses themselves seem to work as pressing on Disagree exits the application.

<img width="1276" alt="image" src="https://github.com/user-attachments/assets/9d16eb50-7240-4c8f-8912-937edf868e29">

**Comment by bolero2074** [comment]
> Running the Mac version (on Sonoma) for the latest release will not allow me to proceed past the Ts and Cs. I get to the screen asking me to agree or disagree but I cannot click on Agree to continue.
> 
> The button presses themselves seem to work as pressing on Disagree exits the application.
> <img alt="image" width="1276" src="https://private-user-images.githubusercontent.com/5353043/387706187-9d16eb50-7240-4c8f-8912-937edf868e29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMzA1MTgsIm5iZiI6MTczMjAzMDIxOCwicGF0aCI6Ii81MzUzMDQzLzM4NzcwNjE4Ny05ZDE2ZWI1MC03MjQwLTRjOGYtODkxMi05MzdlZGY4NjhlMjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTlUMTUzMDE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjI1ZmQxNTJkNDRhZjg1MzhlNzA1NjhmM2JiYmQyZDVhMzg0ZTRmOWFjYTEzOTM4ZTEwYWVmYjdkMDIwY2YwZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.mfccQ4nCKCYvQ8iNCpfnNzDncxTjjcwcVlA3MQRNpgU">

hello, the some issue with windows version, i try portable & setup versions both the some issue,  the button "AGREE" not work.

**Comment by henrikstengaard** [comment]
Hi, I released a new Hst Imager v1.2.396 with fixes for license not disappearing when clicking agree button.
