### ISSUE TITLE
HST Imager GUI version on Windows will not proceed past Terms and Conditions

### ISSUE THREAD

**Issue by bolero2074** [henrikstengaard/hst-imager#19]
hello, Running the Windows Version (portable & setup GUI Version) the latest release, unfortunately not allow me to proceed with the license. I get to the screen asking me to agree or disagree but I cannot click on Agree to continue.

The button presses themselves seem to work as pressing on Disagree exits the application.

https://prnt.sc/d1r7QhRZT3Xq

**Comment by henrikstengaard** [comment]
Hi, I released a new Hst Imager v1.2.396 with fixes for license not disappearing when clicking agree button.
