### ISSUE TITLE
Proposed feature #2 - Change the Mask

### ISSUE THREAD

**Issue by roc-italy** [henrikstengaard/hst-imager#3]
Rarely used features, however if feasible would it be possible adding to the "rdb part add" the mask option?

I have spoiled it in the code with the default value 2147483646 (7ffffffe) which is used in most cases for hard disk images.

The usage that comes to my mind is for images meant for CF cards, where the  0xfffffe mask is used instead of the 0x7ffffffe

Thank you for considering this.

**Comment by henrikstengaard** [comment]
I can add support for setting mask when adding a partition.

Should also be added for part update as well.

**Comment by henrikstengaard** [comment]
New release adds mask option to both rdb part add and update commands and supports either integer value or hex value, so e.g. max transfer can be set to integer value `130560` or hex value `0x1fe00`.
