### ISSUE TITLE
Maybe a little bug - Boot Priority cannot be negative

### ISSUE THREAD

**Issue by roc-italy** [henrikstengaard/hst-imager#5]
Hi Henrik,

My tests are continuing with maybe the most difficult image: The A3000 Dual Boot for KS 1.4 one, which requires 4 partitions (two DOS1 and two PFS3)

I am having some other issue with the format that goes a little mad with either two FS in the RDB or too many partitions to format (but it is too early to raise an issue here, need more testing over the weekend with a fresh mind) 

For now, I believe I have spoiled a little tiny bug. 

The boot-priority in the real amiga can be a negative number (IIRC the range is from -127 to 127), but here it returns some bogus number when set to -1

I could have simply used the boot-priorities from 0 to 4 (5 is normally the floppy) to make it work, but for the sake of completeness of Hst-Imager I wanted to report to you in case you would feel to fix that :-)

![image](https://user-images.githubusercontent.com/40177821/205391893-cf79a5ae-d7c7-46e6-be22-4870237e22e6.png)

This is the full list of commands:

hst.imager.exe blank WB3000.hdf 32GB
hst.imager.exe rdb init WB3000.hdf --size 99%
hst.imager.exe rdb fs add WB3000.hdf pfs3aio PFS3
hst.imager.exe rdb fs add WB3000.hdf FFS_v401 DOS1
hst.imager.exe rdb part add WB3000.hdf WB_1.3 DOS1 1GB --bootable --max-transfer 130560 --buffers 80 --boot-priority -1
hst.imager.exe rdb part add WB3000.hdf WB_2.x DOS1 15MB --bootable --max-transfer 130560 --buffers 80 --boot-priority 1
hst.imager.exe rdb part add WB3000.hdf DH0 PFS3 500MB --max-transfer 130560 --buffers 80
hst.imager.exe rdb part add WB3000.hdf DH1 PFS3 * --max-transfer 130560 --buffers 80
hst.imager.exe rdb part format WB3000.hdf 1 WB13
hst.imager.exe rdb part format WB3000.hdf 2 WB2x
hst.imager.exe rdb part format WB3000.hdf 3 Workbench
hst.imager.exe rdb part format WB3000.hdf 4 Data
hst.imager.exe rdb info WB3000.hdf

**Comment by henrikstengaard** [comment]
Fixed boot priority with negative values in v0.9.255.
